[package]
name = "dezacord"
version = "0.1.0"
edition = "2021"

[dependencies]
zip.workspace = true
fs-err.workspace = true
indexmap.workspace = true
bumpalo.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true